theme: jekyll-theme-cayman
title: Moodsyc
description: Moodysc adalah web yang dapat memberikan rekomendasi musik sesuai dengan sentimen atau perasaan yang sedang dirasakan oleh pengguna. Pengguna dapat dengan mudah menuliskan perasaan yang sedang dirasakan dan nantinya Moodsyc akan memberikan rekomendasi beberapa musik yang sesuai. Yuk tunggu apa lagi, Find your music with moodsyc!
